services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wbdata
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: 123987
    volumes:
      - pg_data:/var/lib/postgresql/data
      - .service-back/DB/user.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  order_service:
    build:
      context: ./service-back
      dockerfile: Dockerfile
    environment:
      KAFKA_CONFIG: "kafka:9092"
      DB_CONFIG: "postgres://tim:123987@postgres:5432/wbdata"
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"

volumes:
  pg_data: