services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./DB/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  order_service:
    build: ./service-back
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"

volumes:
  pg_data: